name: build-service
on:
  push:
    branches: [ main ]
jobs:
  build-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'

      - name: Download
        run: go mod download

      - name: Build
        run: go build -v ./simple-golang.go

