name: pipeline-golang-service
on:
  push:
    branches: [ main ]
env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: be-golang    
  IMAGE_TAG: $(git rev-parse --short "$GITHUB_SHA")
  BRANCH: ${GITHUB_REF#refs/heads/}
jobs:
  build-and-test-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Download
        run: go mod download
      - name: Test
        run: go test -v ./simple-golang.go
      - name: Build
        run: go build -v ./simple-golang.go
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file Dockerfile --tag $DOCKER_USERNAME/$REPO_NAME:${{BRANCH}}-${{IMAGE_TAG}}
      - name: Docker Push
        run: docker push $DOCKER_USERNAME/$REPO_NAME:${{BRANCH}}-${{IMAGE_TAG}}